### ISSUE TITLE
Error in istio-cni dockerfile in Step 14

### ISSUE THREAD

**Issue by aljesusg** [Maistra/istio-images-centos#33]
Step 14/20 : RUN curl -Ls https://copr.fedorainfracloud.org/coprs/g/maistra/istio.el8/repo/rhelbeta-8/group_maistra-istio.el8-rhelbeta-8.repo -o /etc/yum.repos.d/openshift-istio-istio-epel-8.repo &&     microdnf update -y &&     microdnf install -y jq hostname istio-cni-0.12.0 &&     microdnf clean all
 ---> Running in e06808a43a0b

error: No package matches 'jq'
The command '/bin/sh -c curl -Ls https://copr.fedorainfracloud.org/coprs/g/maistra/istio.el8/repo/rhelbeta-8/group_maistra-istio.el8-rhelbeta-8.repo -o /etc/yum.repos.d/openshift-istio-istio-epel-8.repo &&     microdnf update -y &&     microdnf install -y jq hostname istio-cni-0.12.0 &&     microdnf clean all' returned a non-zero code: 1

**Comment by jwendell** [comment]
You need to create the images using a RHEL OS host.
Also, please file issues on Jira: https://issues.jboss.org/projects/MAISTRA/issues

**Comment by luksa** [comment]
@aljesusg yes, sadly, the istio-cni image can only be built on a RHEL8 host for now. The problem is that the jq RPM isn't available in the ubi8 repos (neither ubi-8-baseos, nor ubi-8-appstream).

**Comment by aljesusg** [comment]
Ok thanks @luksa !!!
